#ifndef BANNER_H
#define BANNER_H

static const char banner[] =
"           XXXXXXXXX              XXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXX      XXXXXX           XXXXXX    XXXXXXX\n"
"          XXXXXXXX               XXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXX      XXXXXX           XXXXXX    XXXXXXXX\n"
"         XXXXXXXX               XXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXX      XXXXXX           XXXXXX    XXXXX XXX\n"
"       XXXXXXXXX               XXXXXXXXXXXXXXXXXXXXXX     XXXXXX                  XXXXXX           XXXXXX    XXXXX  XXX\n"
"      XXXXXXXX                XXXXXXXX       XXXXXXX     XXXXXX                  XXXXXX           XXXXXX    XXXXX   XXX\n"
"    XXXXXXXXX----------------XXXXXXX--------XXXXXXX-----XXXXXX----------------->XXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXX\n"
"   XXXXXXXXX----------------XXXXXXX--------XXXXXXX-----XXXXXX----------------->XXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXX\n"
"  XXXXXXXXX                XXXXXXX        XXXXXXX     XXXXXX                  XXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXX\n"
" XXXXXXXX                 XXXXXX         XXXXXXX     XXXXXX                  XXXXXX           XXXXXX    XXXXX       XXX\n"
"XXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXX    XXXXXX           XXXXXX    XXXXX        XXX\n"
"XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXX    XXXXXX           XXXXXX    XXXXX         XXX\n"
"XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXX    XXXXXX           XXXXXX    XXXXX          XXX\n";

#endif /* BANNER_H */
