ifneq (,$(filter aodvv2,$(USEMODULE)))
  USEMODULE += oonf_api
  USEMODULE += oonf_rfc5444
  USEMODULE += manet
endif

ifneq (,$(filter oonf_rfc5444,$(USEMODULE)))
  USEMODULE += oonf_common
endif

ifneq (,$(filter vaina,$(USEMODULE)))
  USEMODULE += gnrc_sock
  USEMODULE += gnrc_sock_udp
endif

ifneq (,$(filter manet,$(USEMODULE)))
  USEMODULE += radio_firmware_net
endif
