ifneq (,$(filter aodvv2,$(USEMODULE)))
  USEMODULE += oonf_api
  USEMODULE += oonf_rfc5444
  USEMODULE += manet
endif

ifneq (,$(filter oonf_rfc5444,$(USEMODULE)))
  USEMODULE += oonf_common
endif

ifneq (,$(filter chat,$(USEMODULE)))
  USEPKG += tinycbor
endif

ifneq (,$(filter manet,$(USEMODULE)))
  USEMODULE += radio_firmware_net
endif

