APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))

BOARD ?= cc1312-launchpad

ifneq (,$(wildcard $(CURDIR)/tests/.))
  DEFAULT_MODULE += test_utils_interactive_sync
endif

EXTERNAL_MODULE_DIRS += $(CURDIR)/../../sys
RADIOBASE = $(CURDIR)/../../
RIOTBASE ?= $(CURDIR)/../../RIOT
QUIET ?= 1
# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1
