MODULE = oonf_regex

CFLAGS += -Wno-char-subscripts
CFLAGS += -Wno-implicit-fallthrough
CFLAGS += -Wno-maybe-uninitialized

NO_AUTO_SRC = 1

SRC += regcomp.c
SRC += regerror.c
SRC += regexec.c
SRC += regfree.c

include $(RIOTBASE)/Makefile.base
