include ../Makefile.tests_common

USEMODULE += gnrc_netdev_default
USEMODULE += radio_firmware_auto_init
USEMODULE += auto_init_gnrc_netif
USEMOUDLE += auto_init_aodvv2
USEMODULE += auto_init_rfc5444
USEMODULE += gnrc_ipv6_router
USEMODULE += aodvv2

include $(RIOTBASE)/Makefile.include
