include ../Makefile.tests_common

TESTS := "$(CURDIR)/tests/01-run.py"

USEMODULE += embunit
USEMODULE += rfc5444
USEMODULE += netdev_eth
USEMODULE += netdev_test
USEMODULE += gnrc_netif

include $(RIOTBASE)/Makefile.include
