include ../Makefile.tests_common

USEMODULE += gnrc_netdev_default
USEMODULE += gnrc_ipv6_router
USEMODULE += auto_init_gnrc_netif
USEMODULE += radio_firmware_auto_init
USEMODULE += auto_init_rfc5444
USEMODULE += gnrc_ipv6_router
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += rfc5444

include $(RIOTBASE)/Makefile.include
